version: '3.8'

services:
  frontend:
    build: 
      context: .
      dockerfile: src/Dockerfile
    ports:
      - "3000:80"
    environment:
      VITE_API_URL: http://api:8080
    depends_on:
      - api
    networks:
      - app-network

  api:
    build: ./server
    ports:
      - "8080:8080"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge